### ISSUE TITLE
US37 - Acessar meus posts

### ISSUE THREAD

**Issue by Matias0422** [carlosaragon/Requisitos-9GAG-2-2017#29]
Eu como usuário [logado](https://github.com/carlosaragon/Requisitos-9GAG-2-2017/wiki/Logado) desejo acessar minhas [postagens](https://github.com/carlosaragon/Requisitos-9GAG-2-2017/wiki/Meme) para ter conhecimento sobre minhas [postagens](https://github.com/carlosaragon/Requisitos-9GAG-2-2017/wiki/Meme).
---

### Critérios de aceitação

- [ ] O usuário deve estar [logado](https://github.com/carlosaragon/Requisitos-9GAG-2-2017/wiki/Logado).
- [ ] Deve ser uma opção dentro da issue #27, respeitando aos mesmos critérios.
- [ ] Deve ser listado todas as [postagens](https://github.com/carlosaragon/Requisitos-9GAG-2-2017/wiki/Meme) feitas pelo usuário [logado](https://github.com/carlosaragon/Requisitos-9GAG-2-2017/wiki/Logado).
- [ ] Cada [postagem](https://github.com/carlosaragon/Requisitos-9GAG-2-2017/wiki/Meme) listada deve ser [linkada](https://github.com/carlosaragon/Requisitos-9GAG-2-2017/wiki/Url) para acesso, entrando na issue #6 .
- [ ] Deve mostrar [link](https://github.com/carlosaragon/Requisitos-9GAG-2-2017/wiki/Url) para criar [postagem](https://github.com/carlosaragon/Requisitos-9GAG-2-2017/wiki/Meme) referente a issue #1, caso o usuário não tenha feito [postagens](https://github.com/carlosaragon/Requisitos-9GAG-2-2017/wiki/Meme).
- [ ] A ordenação dos [posts](https://github.com/carlosaragon/Requisitos-9GAG-2-2017/wiki/Meme) feito pelo usuário deve ser do mais recente ao mais antigo ([Fresh](https://github.com/carlosaragon/Requisitos-9GAG-2-2017/wiki/Fresh)).
